### ISSUE TITLE
Functionality fails after refreshing the page

### ISSUE THREAD

**Issue by gyl-coder** [ataft/plugin-image-zoom#2]
When I first entered a document with a picture, this function works. But when I refresh the page, the function fails

**Comment by ataft** [comment]
It's hard to say without looking at a working example and/or repo.

Perhaps you can take a look at my site (https://learn.flexitanalytics.com/) and repo (https://github.com/ataft/flexit-docs). Hope that helps.

**Comment by xgarrett** [comment]
Hello,
@ataft it happens in conjunction with `@docusaurus/plugin-ideal-image`. I guess that's the issue with `setTimeout(/*...*/, 100)` in `zoom.js` (after increasing it to 1000 it works - but this is not a proper solution).

Basically `@docusaurus/plugin-ideal-image` renders `svg` with blurred image until real image is loading and later on replaces `svg` with proper `img`.

**Comment by ataft** [comment]
Thanks @xgarrett , this seems to work. As you say, maybe not the proper solution, but ok for now. Fixed in version 1.1 of this plugin.
