### ISSUE TITLE
User Guide Missing

### ISSUE THREAD

**Issue by gbriere** [ataft/plugin-image-zoom#3]
Hi, 

I'm very interesting by your plugin and I'd like to install it on my Docusaurus website. Can you explain how this is working please ? 

Thank you !

**Comment by ataft** [comment]
It's in the readme, https://github.com/ataft/plugin-image-zoom. Simply install the plugin and add it to your Docusaurus config:
https://docusaurus.io/docs/using-plugins

`img` tags will then be zoomable, using the 'medium-zoom' library
